### PR TITLE
Test as application.

### PR DESCRIPTION
**Pull request by flexconstructor**
Runs simple application build and test script for testing docker image.

- The run test script has been updated
- The test as applications has been added.

### CODE REVIEW

**Comment by tyranron** [comment]
@flexconstructor for future cases: there is no reason to make PR from forked repo. You are the member of team, so just create feature branch and PR for it as we do in common workflow.

**Review by tyranron — APPROVED** [review]
Nicely done, except some code style inconsistencies.

**Review by tyranron — CHANGES_REQUESTED** [review]
Oops, didn't notice that spec assertion was commented.

@flexconstructor any explanations?

**Comment by flexconstructor** [comment]
@tyranron , Fixed `flashplayerdebugger runs ok`. Lost imports in test.as. Definitely it is necessary to work during the day.

**Review by tyranron — APPROVED** [review]

**Review by tyranron — APPROVED** [review]
@flexconstructor can be squashed and merged.

**Pull request merged**
